apiVersion: v1
kind: Service
metadata:
  name: content-service
spec:
  type: NodePort
  selector:
    app: content-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000    # ✅ FIXED
      nodePort: 30007