apiVersion: v1
kind: Service
metadata:
  name: kub-service
spec:
  type: NodePort
  selector:
    app: kub-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003    # ✅ FIXED
      nodePort: 30383