pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                bat 'docker build -t flask-sms-app .'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'python -m unittest discover || echo No tests found'
            }
        }

        stage('Run Container') {
            steps {
                bat 'docker run -d -p 3000:3000 -v %cd%/data:/app/data --name flask-sms flask-sms-app'
            }
        }
    }
}